### ISSUE TITLE
Documentation does not show up at TER

### ISSUE THREAD

**Issue by thomaszbz** [cyberhouse/typo3-doctrine-orm#1]
As of released version 1.0.0: Documentation does not show up at TER

Please contact the t3o team in case this does not originate from the code of the extension. I've seen that happen years ago (hopefully not an issue any more).

![auswahl_319](https://cloud.githubusercontent.com/assets/11200727/26761759/0bba56f8-4936-11e7-88c0-84efc20c6b4c.png)

**Comment by garfieldius** [comment]
Did not notice, thx for pointing it out. Will have a look at it.

**Comment by garfieldius** [comment]
Some issue with the rendering at the server, fixed now: <https://docs.typo3.org/typo3cms/extensions/doctrine_orm/>

Thx to @marble for helping out on this
